import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacy Policy", description: "Learn how QuickSquad, owned and operated by A V TRADE CORPORATION, collects, uses, and protects customer information.", alternates: { canonical: "/privacy-policy" } };

const sections = [
  ["Information we collect", "Depending on how you use QuickSquad, we may collect contact details such as your name, email address, and phone number; the content of service inquiries; subscription details; and technical usage information such as device, browser, IP address, and pages visited."],
  ["How we use information", "We use information to respond to requests, deliver and improve consultation services, process subscriptions or billing where applicable, maintain site security, communicate service updates, and meet legal obligations."],
  ["When information is shared", "We do not sell personal information. We may share it with service providers that help operate the platform, process payments, provide customer support, or secure systems; and with authorities where required by law. These parties may use information only to perform their services or meet legal requirements."],
  ["Cookies and analytics", "QuickSquad may use cookies and similar technologies to remember preferences, understand site use, improve performance, and measure marketing. You can manage cookies through browser settings, although some site features may be affected."],
  ["Data security and retention", "We use reasonable administrative, technical, and organizational safeguards designed to protect information. No internet transmission or storage system is completely secure. We retain information only for as long as needed for the purposes described here, including legal, accounting, and dispute-resolution requirements."],
  ["Your choices", "You may ask to access, correct, delete, or limit the use of personal information, or opt out of promotional messages. Some requests may be limited where we must retain information by law or to protect the platform and its users."],
];

export default function PrivacyPolicy() {
  return <main className="bg-slate-50 px-6 py-16 text-slate-800"><article className="mx-auto max-w-4xl rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-12"><p className="text-sm font-bold uppercase tracking-[.16em] text-blue-700">QuickSquad legal</p><h1 className="mt-3 text-4xl font-bold text-slate-950">Privacy Policy</h1><p className="mt-5 text-lg leading-8 text-slate-600">This Privacy Policy describes how QuickSquad, owned and operated by A V TRADE CORPORATION, collects, uses and protects customer information.</p><p className="mt-5 leading-7 text-slate-600">A V TRADE CORPORATION is a registered partnership firm and manages QuickSquad’s services, customer support, billing, subscriptions, marketing, and operations.</p><div className="mt-10 space-y-8">{sections.map(([title, text], index) => <section key={title}><h2 className="text-xl font-bold text-slate-900">{index + 1}. {title}</h2><p className="mt-3 leading-7 text-slate-600">{text}</p></section>)}</div><section className="mt-10 border-t border-slate-200 pt-8"><h2 className="text-xl font-bold text-slate-900">Contact and changes</h2><p className="mt-3 leading-7 text-slate-600">For privacy questions or requests, email <a className="font-semibold text-blue-700 underline" href="mailto:support@quicksquad.live">support@quicksquad.live</a>. We may update this policy from time to time; the current version will be posted on this page. Please also review our <Link className="font-semibold text-blue-700 underline" href="/terms-of-service">Terms of Service</Link> and <Link className="font-semibold text-blue-700 underline" href="/disclaimer">Disclaimer</Link>.</p></section><p className="mt-8 text-sm text-slate-500">Effective date: August 11, 2026</p></article></main>;
}
