import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Terms of Service", description: "QuickSquad terms of service and important boundaries for general consumer consultation.", alternates: { canonical: "/terms-of-service" } };

const sections = [
  ["Acceptance", "By using the QuickSquad website, requesting a consultation, or purchasing a subscription, you agree to these Terms and the linked Privacy Policy, Refund Policy, and Disclaimer."],
  ["What QuickSquad provides", "QuickSquad provides AI-powered information assistance and general consultation for everyday questions and online tasks. We may help you research options, understand common processes, organize information, and identify useful next steps."],
  ["Important professional boundaries", "Information on QuickSquad is educational and general. It is not professional legal advice, investment advice, medical advice, tax advice, or any other regulated professional advice. QuickSquad is not a bank, law firm, medical provider, financial adviser, or government agency. Consult an appropriately qualified professional before making decisions where professional advice is required."],
  ["Your responsibilities", "You are responsible for the accuracy of information you submit, protecting your accounts and credentials, reviewing information before acting on it, and making your own decisions. Do not share passwords, bank-card details, or other highly sensitive information unless specifically requested through an approved and secure process."],
  ["Payments and subscriptions", "Where a paid service or subscription is offered, prices, billing frequency, and applicable terms will be shown before purchase. Refund requests are handled under our Refund Policy."],
  ["Acceptable use and availability", "You must use the platform lawfully and must not misuse it, disrupt it, attempt unauthorized access, submit harmful content, or use it to commit fraud. We may change, suspend, or discontinue parts of the platform to maintain security, comply with law, or improve our services."],
  ["Liability", "To the extent permitted by law, QuickSquad is not responsible for decisions, losses, or outcomes resulting from reliance on general information, third-party resources, service interruptions, or events outside our reasonable control."],
];

export default function TermsOfService() {
  return <main className="bg-slate-50 px-6 py-16 text-slate-800"><article className="mx-auto max-w-4xl rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-12"><p className="text-sm font-bold uppercase tracking-[.16em] text-blue-700">QuickSquad legal</p><h1 className="mt-3 text-4xl font-bold text-slate-950">Terms of Service</h1><div className="mt-10 space-y-8">{sections.map(([title, text], index) => <section key={title}><h2 className="text-xl font-bold text-slate-900">{index + 1}. {title}</h2><p className="mt-3 leading-7 text-slate-600">{text}</p></section>)}</div><section className="mt-10 border-t border-slate-200 pt-8"><h2 className="text-xl font-bold text-slate-900">Contact and updates</h2><p className="mt-3 leading-7 text-slate-600">For questions, contact <a className="font-semibold text-blue-700 underline" href="mailto:support@quicksquad.live">support@quicksquad.live</a>. We may update these Terms by posting a revised version here. Read the <Link className="font-semibold text-blue-700 underline" href="/privacy-policy">Privacy Policy</Link>, <Link className="font-semibold text-blue-700 underline" href="/refund-policy">Refund Policy</Link>, and <Link className="font-semibold text-blue-700 underline" href="/disclaimer">Disclaimer</Link>.</p></section><p className="mt-8 text-sm text-slate-500">Effective date: August 11, 2026</p></article></main>;
}
