import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Disclaimer", description: "Important limitations and disclosures for QuickSquad's general consumer consultation services, operated by A V TRADE CORPORATION.", alternates: { canonical: "/disclaimer" } };

const sections = [
  ["General information only", "QuickSquad provides general, educational information and consumer consultation to help users understand everyday questions and online tasks. Information on this site and in consultations is not tailored professional advice and may not be complete, current, or suitable for your circumstances."],
  ["No regulated professional service", "QuickSquad and A V TRADE CORPORATION are not a bank, law firm, medical provider, financial adviser, investment adviser, tax adviser, insurance provider, or government agency. We do not open accounts, make decisions for government agencies, diagnose or treat medical conditions, give legal opinions, or recommend investments."],
  ["No fiduciary relationship", "Using QuickSquad does not create a fiduciary relationship. You remain responsible for evaluating information, considering your personal circumstances, and deciding whether to take any action."],
  ["No attorney-client relationship", "Nothing provided by QuickSquad is legal advice or creates an attorney-client relationship. For legal issues, deadlines, documents, rights, or obligations, consult a licensed attorney or other qualified legal professional in the relevant jurisdiction."],
  ["No doctor-patient relationship", "Health-related information is provided for general educational purposes only and does not create a doctor-patient relationship. It is not a diagnosis, treatment plan, or substitute for professional medical care. Seek urgent medical assistance immediately for emergencies."],
  ["No investment-adviser relationship", "Financial and banking information is general and educational only. It is not investment advice, a recommendation, an offer, or a solicitation to buy or sell any security or financial product. Consult a qualified financial professional before making financial or investment decisions."],
  ["Government and third-party resources", "We may help users locate official portals or third-party resources. QuickSquad is not affiliated with, endorsed by, or authorized to act for any government agency unless expressly stated. Third-party websites, services, prices, policies, and outcomes are outside our control."],
  ["Your decisions", "You are solely responsible for your decisions, actions, and results. Before relying on information involving health, law, investments, taxes, banking, government benefits, or any regulated area, consult a qualified professional or the relevant official source."],
];

export default function DisclaimerPage() {
  return <main className="bg-slate-50 px-6 py-16"><article className="mx-auto max-w-4xl rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-12"><p className="text-sm font-bold uppercase tracking-[.16em] text-blue-700">Important information</p><h1 className="mt-3 text-4xl font-bold text-slate-950">Disclaimer</h1><p className="mt-5 text-lg leading-8 text-slate-600">QuickSquad is a consumer-facing AI-powered consultation platform owned and operated by A V TRADE CORPORATION, a registered partnership firm.</p><div className="mt-10 space-y-8">{sections.map(([title, text], index) => <section key={title}><h2 className="text-xl font-bold text-slate-900">{index + 1}. {title}</h2><p className="mt-3 leading-7 text-slate-600">{text}</p></section>)}</div><p className="mt-10 border-t border-slate-200 pt-8 leading-7 text-slate-600">Questions about these limitations can be sent to <a className="font-semibold text-blue-700 underline" href="mailto:support@quicksquad.live">support@quicksquad.live</a>. Please read our <Link className="font-semibold text-blue-700 underline" href="/terms-of-service">Terms of Service</Link> and <Link className="font-semibold text-blue-700 underline" href="/privacy-policy">Privacy Policy</Link>.</p></article></main>;
}
